name: Continuous integration

on:
  push:
    branches: [deploy]
  pull_request:
    branches: [deploy]

jobs:
  build-emscripten:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install python3 cmake emscripten ninja-build
      - name: Configure
        run: emcmake cmake -DPLATFORM=Web -B build -S . -G Ninja
      - name: Build with CMake
        run: cmake --build build -j 4
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: "build"
  deploy-to-gh-pages:
    needs: build-emscripten
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
  upload-distribution:
    name: Upload distribution for platform `${{matrix.config.name}}`
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: release-linux-gnu,
              fancy_name: Linux (GCC),
              exe: Bombswab,
              out: Bombswab,
              os: ubuntu-latest,
              cxx: g++,
              cc: gcc,
            }
          - {
              name: release-win-msvc,
              fancy_name: Windows (MSVC),
              exe: Debug/Bombswab.exe,
              out: Bombswab.exe,
              os: windows-latest,
              cxx: cl,
              cc: cl,
            }
    steps:
      - name: Install dependencies (Ubuntu)
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install cmake gcc g++ libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libgl-dev
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Configure CMake with selected compiler family
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=${{matrix.config.cc}} -DCMAKE_CXX_COMPILER=${{matrix.config.cxx}} -S ${{github.workspace}}
      - name: Build with CMake
        run: cmake --build build -j 4
      - name: Copy the executable into the root folder
        run: cp build/${{matrix.config.exe}} ${{matrix.config.out}}
      - name: Tar the distribution
        run: tar -cvf ${{matrix.config.name}}.tar ${{matrix.config.out}} assets
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.config.fancy_name}}
          path: ${{matrix.config.name}}.tar
