name: CI with CMake

on:
  push:
    branches: [main, github-actions]
  pull_request:
    branches: [main, github-actions]

jobs:
  produce-release-artifacts:
    name: Produce release artifacts for platform `${{matrix.config.name}}`
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: release-linux-gnu,
              fancy_name: Linux (GCC),
              exe: BasharQuest,
              os: ubuntu-latest,
              cxx: g++,
              cc: gcc,
            }
          - {
              name: release-win-msvc,
              fancy_name: Windows (MSVC),
              exe: BasharQuest.exe,
              os: windows-latest,
              cxx: cl,
              cc: cl,
            }
    steps:
      - name: Install dependencies (Ubuntu)
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install cmake gcc g++ libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libopengl-dev
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Configure CMake with selected compiler family
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=${{matrix.config.cc}} -DCMAKE_CXX_COMPILER=${{matrix.config.cxx}} ${{github.workspace}}
      - name: Build with CMake
        run: cmake --build build -j 4
      - name: Package into an archive
        uses: vimtor/action-zip@v1.1
        with:
          files: build/${{matrix.config.exe}} build/assets/
          dest: ${{matrix.config.name}}.zip
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.config.fancy_name}}
          path: ${{matrix.config.name}}.zip
